import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { LogsListener } from "@/components/logs-listener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Check for required environment variables
const checkEnvironmentVariables = () => {
  // Only run on the server during development
  if (typeof window === 'undefined' && process.env.NODE_ENV === 'development') {
    const requiredVariables = [
      'AWS_REGION',
      'AWS_ACCESS_KEY_ID',
      'AWS_SECRET_ACCESS_KEY',
      'UPLOAD_BUCKET_NAME',
      'RETRAIN_LAMBDA_NAME'
    ];
    
    const missing = requiredVariables.filter(v => !process.env[v]);
    
    if (missing.length > 0) {
      console.warn('\x1b[33m%s\x1b[0m', '⚠️ Warning: Missing environment variables:');
      missing.forEach(v => console.warn('\x1b[33m%s\x1b[0m', `   - ${v}`));
      console.warn('\x1b[33m%s\x1b[0m', 'Create a .env.local file with these variables or set them in your environment.');
    } else {
      console.log('\x1b[32m%s\x1b[0m', '✅ All required environment variables are set.');
    }
    
    // Log the actual value of UPLOAD_BUCKET_NAME for debugging
    console.log('\x1b[36m%s\x1b[0m', `ℹ️ UPLOAD_BUCKET_NAME: ${process.env.UPLOAD_BUCKET_NAME || '(not set)'}`);
  }
};

// Call the check function
checkEnvironmentVariables();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <LogsListener />
        {children}
      </body>
    </html>
  );
}
